// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oauvtcbancaiwlxbmxxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hdXZ0Y2JhbmNhaXdseGJteHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTQwMjcsImV4cCI6MjA2NDY5MDAyN30.Oz4hUpy6zAcyqRkU4vSEwU5orlNuVwvXncO7mXEDNmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);